URL_carta = ['http://217.182.201.195:7777/up/world/world/',
             'http://145.239.134.46:7788/up/world/world/',
             'http://145.239.134.46:7777/up/world/world/',
             'http://148.251.76.169:7788/up/world/world/',
             'http://51.75.53.36:8878/up/world/world/',
             'http://95.217.194.41:8877/up/world/world/',
             'http://51.75.55.87:8877/up/world/world/',
             'http://51.75.55.87:8878/up/world/world/',
             'http://217.182.201.210:8888/up/world/world/',
             'http://148.251.76.169:8888/up/world/world/',
             'http://95.217.194.41:7778/up/world/world/',
             'http://95.217.194.41:8870/up/world/world/',
             # 'terrafirmacraft',
             'http://51.75.53.35:7788/up/world/world/',
             # 'terawars',
             'http://51.75.53.35:8877/up/world/world/',
             'http://51.75.53.36:8888/up/world/world/'
             ]
server = ['Classic',
          'HiTech',
          'HiTech2',
          'Industrial',
          'Divine',
          'RPG',
          'TechnoMagic',
          'TechnoMagic2',
          'Pixelmon',
          'GalaxyCraft',
          'HungerGames',
          'Magic',
          'OneBlock',
          'TMSkyBlock',
          'HiTech3']
# 'Pixelmon2',
URL_md = [
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=0',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=12',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=7',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=20',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=15',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=38',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=16',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=26',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=17',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=23',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=13',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=19',
    # 'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=33',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=35',
    # 'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=1',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=31',
    'https://minecraftonly.ru/engine/scripts/moderators.php?action=showmoders&serverid=32'
]
